apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: busyboxes.zerodayz.example.com
spec:
  group: zerodayz.example.com
  names:
    kind: Busybox
    listKind: BusyboxList
    plural: busyboxes
    singular: busybox
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Busybox is the Schema for the busyboxes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BusyboxSpec defines the desired state of Busybox
            properties:
              size:
                description: Size is the size of the busybox deployment
                format: int32
                type: integer
            required:
            - size
            type: object
          status:
            description: BusyboxStatus defines the observed state of Busybox
            properties:
              nodes:
                description: Nodes are the names of the busybox pods
                items:
                  type: string
                type: array
            required:
            - nodes
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
