apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: busybox-operator
  template:
    metadata:
      labels:
        name: busybox-operator
    spec:
      serviceAccountName: busybox-operator
      containers:
        - name: busybox-operator
          # Replace this with the built image name
          image: quay.io/zerodayz/busybox-operator:v0.0.1
          command:
          - busybox-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "busybox-operator"
